ApiKey: "your-api-key-here"
AppName: "MyApp"
AppVersion: "1.0.0"
BaseUrl: "http://localhost:8080"
Environment: "development" # development, staging, uat, prod
ServerPort: 8080

db:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  db_name: "myapp_db"
  max_idle_connection: 10
  max_open_connection: 100
  conn_max_lifetime_minutes: 30
  logging: "true"
  ssl_mode: "disable"

jwt:
  access_token_expiry_min: 15
  refresh_token_expiry_min: 1440
  access_token_secret: "your-access-secret"
  refresh_token_secret: "your-refresh-secret"

log:
  level: "debug" # debug, info, warn, error
  format: "json" # console, json
  enable_caller: true
  enable_stacktrace: false

cache:
  driver: "redis"
  addr: "localhost:6379"
  password: ""
  db: 0
  REDIS_CONNECTION_LIMIT: 50
  USE_REDIS: true

aws:
  aws_region: "ap-south-1"
  aws_access_key_id: "your-access-key"
  aws_secret_access_key: "your-secret-key"
  aws_s3_bucket_name: "your-bucket-name"
  aws_signed_url_expiry: 3600 # seconds
  max_file_size: 52428800 #50MB

cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://127.0.0.1:5500"
    - "http://localhost:5500"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "x-api-key"
    - "reset-token"
    - "refresh-token"
  expose_headers:
    - "Content-Length"
  allow_credentials: true
  max_age_hours: 12

email:
  host: "smtp.gmail.com"
  port: 587
  username: "your-email@gmail.com"
  password: "your-email-password"
  from: "no-reply@myapp.com"
  provider: "smtp"

service_base_url:
  communication_service: "http://localhost:5000"

password_reset:
  reset_link: "http://localhost:3000/reset-password"
  reset_link_expiry_min: 30

crypto:
  aes_key: "your-32-byte-aes-key-here"

